// Code generated by go-swagger; DO NOT EDIT.


// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0


package policy

import (
  "net/http"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime/middleware"
  "github.com/go-openapi/runtime/security"
  "github.com/go-openapi/strfmt"
  "github.com/go-openapi/swag/conv"
  "github.com/go-openapi/swag/jsonutils"
  "github.com/go-openapi/swag/stringutils"
  "github.com/go-openapi/swag/typeutils"
  "github.com/go-openapi/validate"

  	"github.com/cilium/cilium/api/v1/models"
	"github.com/cilium/cilium/api/v1/server/restapi/bgp"
	"github.com/cilium/cilium/api/v1/server/restapi/daemon"
	"github.com/cilium/cilium/api/v1/server/restapi/endpoint"
	"github.com/cilium/cilium/api/v1/server/restapi/ipam"
	"github.com/cilium/cilium/api/v1/server/restapi/policy"
	"github.com/cilium/cilium/api/v1/server/restapi/prefilter"
	"github.com/cilium/cilium/api/v1/server/restapi/service"
  	"github.com/cilium/cilium/api/v1/server/restapi"
)

// GetIdentityEndpointsHandlerFunc turns a function with the right signature into a get identity endpoints handler
type GetIdentityEndpointsHandlerFunc func(GetIdentityEndpointsParams) middleware.Responder 
  

// Handle executing the request and returning a response
func (fn GetIdentityEndpointsHandlerFunc) Handle(params GetIdentityEndpointsParams) middleware.Responder  {
  return fn(params)
}

// GetIdentityEndpointsHandler interface for that can handle valid get identity endpoints params
type GetIdentityEndpointsHandler interface {
  Handle(GetIdentityEndpointsParams) middleware.Responder 
    
}

// NewGetIdentityEndpoints creates a new http.Handler for the get identity endpoints operation
func NewGetIdentityEndpoints(ctx *middleware.Context, handler GetIdentityEndpointsHandler) *GetIdentityEndpoints {
  return &GetIdentityEndpoints{Context: ctx, Handler: handler}
}

/* GetIdentityEndpoints swagger:route GET /identity/endpoints policy getIdentityEndpoints

Retrieve identities which are being used by local endpoints

*/
type GetIdentityEndpoints struct {
  Context *middleware.Context
  Handler GetIdentityEndpointsHandler
}

func (o *GetIdentityEndpoints) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
  route, rCtx, _ := o.Context.RouteInfo(r)
  if rCtx != nil {
    *r = *rCtx
  }
  params := NewGetIdentityEndpointsParams()
  if err := o.Context.BindValidRequest(r, route, &params); err != nil { // bind params
    o.Context.Respond(rw, r, route.Produces, route, err)
    return
  }

  
    res := o.Handler.Handle(params) // actually handle the request
  

  o.Context.Respond(rw, r, route.Produces, route, res)

}


