


// Code generated by go-swagger; DO NOT EDIT.


// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0


package policy

import (
  "fmt"
  "net/http"

  "github.com/go-openapi/errors"
  "github.com/go-openapi/runtime"
  "github.com/go-openapi/runtime/security"
  "github.com/go-openapi/validate"
  "github.com/go-openapi/runtime/middleware"
  "github.com/go-openapi/swag/conv"
  "github.com/go-openapi/swag/jsonutils"
  "github.com/go-openapi/swag/stringutils"
  "github.com/go-openapi/swag/typeutils"
  	"github.com/cilium/cilium/api/v1/models"
	"github.com/cilium/cilium/api/v1/server/restapi/bgp"
	"github.com/cilium/cilium/api/v1/server/restapi/daemon"
	"github.com/cilium/cilium/api/v1/server/restapi/endpoint"
	"github.com/cilium/cilium/api/v1/server/restapi/ipam"
	"github.com/cilium/cilium/api/v1/server/restapi/policy"
	"github.com/cilium/cilium/api/v1/server/restapi/prefilter"
	"github.com/cilium/cilium/api/v1/server/restapi/service"
  	"github.com/cilium/cilium/api/v1/server/restapi"
)



// GetPolicySubjectSelectorsOKCode is the HTTP code returned for type GetPolicySubjectSelectorsOK
const GetPolicySubjectSelectorsOKCode int = 200

/*GetPolicySubjectSelectorsOK Success

swagger:response getPolicySubjectSelectorsOK
*/
type GetPolicySubjectSelectorsOK struct {
  
  
  /*
  In: Body
  */
  Payload models.SelectorCache `json:"body,omitempty"`
  
}

// NewGetPolicySubjectSelectorsOK creates GetPolicySubjectSelectorsOK with default headers values
func NewGetPolicySubjectSelectorsOK() *GetPolicySubjectSelectorsOK { 

  return &GetPolicySubjectSelectorsOK{
    
    }
}


// WithPayload adds the payload to the get policy subject selectors o k response
func (o *GetPolicySubjectSelectorsOK) WithPayload(payload models.SelectorCache) *GetPolicySubjectSelectorsOK {
  o.Payload = payload
  return o
}

// SetPayload sets the payload to the get policy subject selectors o k response
func (o *GetPolicySubjectSelectorsOK) SetPayload(payload models.SelectorCache) {
  o.Payload = payload
}


// WriteResponse to the client
func (o *GetPolicySubjectSelectorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {
  
  
  rw.WriteHeader(200)
    payload := o.Payload
    if payload == nil {
      // return empty array
      payload =models.SelectorCache{}
    }
    
    if err := producer.Produce(rw, payload); err != nil {
      panic(err) // let the recovery middleware deal with this
    }
}







