// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

import (
  stderrors "errors"

  "github.com/go-openapi/strfmt"
  	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/netutils"
	"github.com/go-openapi/swag/stringutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// BgpNlri Network Layer Reachability Information (NLRI) of the path
//
// swagger:model BgpNlri
      type BgpNlri struct {
  
  
    // Base64-encoded NLRI in the BGP UPDATE message format
Base64 string `json:"base64,omitempty"`

  
  
}
  
// Validate validates this bgp nlri
func (m *BgpNlri) Validate(formats strfmt.Registry) error {
  return nil
}
// ContextValidate validates this bgp nlri based on context it is used 
func (m *BgpNlri) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
  return nil
}
  
// MarshalBinary interface implementation
func (m *BgpNlri) MarshalBinary() ([]byte, error) {
  if m == nil {
    return nil, nil
  }
  return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BgpNlri) UnmarshalBinary(b []byte) error {
  var res BgpNlri
  if err := jsonutils.ReadJSON(b, &res); err != nil {
    return err
  }
  *m = res
  return nil
}



