// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

import (
  stderrors "errors"

  "github.com/go-openapi/strfmt"
  	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/netutils"
	"github.com/go-openapi/swag/stringutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// EndpointBatchDeleteRequest Properties selecting a batch of endpoints to delete.
// 
//
// swagger:model EndpointBatchDeleteRequest
      type EndpointBatchDeleteRequest struct {
  
  
    // ID assigned by container runtime
ContainerID string `json:"container-id,omitempty"`

  
  
}
  
// Validate validates this endpoint batch delete request
func (m *EndpointBatchDeleteRequest) Validate(formats strfmt.Registry) error {
  return nil
}
// ContextValidate validates this endpoint batch delete request based on context it is used 
func (m *EndpointBatchDeleteRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
  return nil
}
  
// MarshalBinary interface implementation
func (m *EndpointBatchDeleteRequest) MarshalBinary() ([]byte, error) {
  if m == nil {
    return nil, nil
  }
  return jsonutils.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EndpointBatchDeleteRequest) UnmarshalBinary(b []byte) error {
  var res EndpointBatchDeleteRequest
  if err := jsonutils.ReadJSON(b, &res); err != nil {
    return err
  }
  *m = res
  return nil
}



