// Code generated by go-swagger; DO NOT EDIT.

// Copyright Authors of Cilium
// SPDX-License-Identifier: Apache-2.0

package models

import (
  stderrors "errors"

  "github.com/go-openapi/strfmt"
  	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag/conv"
	"github.com/go-openapi/swag/jsonutils"
	"github.com/go-openapi/swag/netutils"
	"github.com/go-openapi/swag/stringutils"
	"github.com/go-openapi/swag/typeutils"
	"github.com/go-openapi/validate"
)

// LabelArrayList LabelArrayList is an array of LabelArrays forming a set
//
// swagger:model LabelArrayList
    type LabelArrayList []LabelArray
  
    
  
  
  
// Validate validates this label array list
func (m LabelArrayList) Validate(formats strfmt.Registry) error {
  var res []error
  
  
  
    
  
  
  
  
  
  
  
      for i := 0; i < len(m); i++ {
        
    
  
  
  
  
  
  
  
      if err := m[i].Validate(formats); err != nil {
        ve := new(errors.Validation)
        if stderrors.As(err, &ve) {
          return ve.ValidateName(strconv.Itoa(i))
        }
        ce := new(errors.CompositeError)
        if stderrors.As(err, &ce) {
          return ce.ValidateName(strconv.Itoa(i))
        }

        return err
      }


      }


  
  
  

  if len(res) > 0 {
    return errors.CompositeValidationError(res...)
  }
  return nil
}

  
  

  

    
// ContextValidate validate this label array list based on the context it is used
func (m LabelArrayList) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
  var res []error
   
  
    
  
  
      for i := 0; i < len(m); i++ {
        
    
  
  
      if err := m[i].ContextValidate(ctx, formats); err != nil {
        ve := new(errors.Validation)
        if stderrors.As(err, &ve) {
          return ve.ValidateName(strconv.Itoa(i))
        }
        ce := new(errors.CompositeError)
        if stderrors.As(err, &ce) {
          return ce.ValidateName(strconv.Itoa(i))
        }

        return err
      }



      }



  
  if len(res) > 0 {
    return errors.CompositeValidationError(res...)
  }
  return nil
}


   
   




